name: PlotsX
version: ${version}
description: ${description}
api-version: '1.20.6'
folia-supported: true

authors: [SyntaxDevTeam]
website: https://github.com/SyntaxDevTeam/PlotsX
support:
  issues: https://github.com/SyntaxDevTeam/PlotsX/issues
  updates: https://github.com/SyntaxDevTeam/PlotsX/releases

localization:
  available: [en_US, pl_PL, fr_FR, es_ES, de_DE]
  default: en_US

main: pl.syntaxdevteam.plotsx.PlotsX
loader: pl.syntaxdevteam.plotsx.loader.SyntaxLoader
has-open-classloader: false

softdepend: [Folia]

features:
  debug: true

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    MiniPlaceholders:
      load: BEFORE
      required: false
    LuckPerms:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
    VaultUnlocked:
      load: BEFORE
      required: false
    CleanerX:
      load: BEFORE
      required: false
    CoreProtect:
      load: BEFORE
      required: false
